import type { Metadata } from 'next'
import { Inter, Open_Sans, Noto_Sans, Montserrat } from 'next/font/google'
import './globals.css'
import '@radix-ui/themes/styles.css'; 
import { Theme } from '@radix-ui/themes';
import { gray } from '@radix-ui/colors'
import localFont from 'next/font/local'



const ppmori = localFont({
  src: '../public/fonts/PPMori-Regular.otf',
  variable: '--ppMori',
  weight: '400',
})


const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--openSans",
  weight: ['400', '500', '700']
});

const notoSans = Noto_Sans({
  subsets: ["latin"],
  variable: "--notoSans",
  weight: ['400', '500', '700']
});

const mont = Montserrat({
  subsets: ["latin"],
  variable: "--mont",
  weight: ['400', '500', '700']
});

const sfpromed = localFont({
  src: '../public/fonts/sfpromed.otf',
  variable: '--sfpromed',
  weight: '400, 500'
})
const sfproreg = localFont({
  src: '../public/fonts/sfproreg.otf',
  variable: '--ppMori',
  weight: '400',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"> 
      <body className='bg-[#e1dfdd] dark:bg-[#191825] overflow-x-hidden font-sfpromed'>
        {children}
      </body>
    </html>
  )
}
