import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Hero from '@/components/Hero'
import Navbar from '@/components/Navbar'
import { ThemeProvider } from '@/components/theme-provider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="font-inter">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
        <div className="flex h-screen">
          <div className="w-1/2 overflow-hidden text-center py-24">
            <Hero />
            <Navbar />
          </div>
          <div className="w-1/2 overflow-auto ">
            {children}
          </div>
        </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
